apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
spec:
  capacity:
    storage: 8Gi  
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
  hostPath:
    path: /data/prometheus  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alert-manager-pv
spec:
  capacity:
    storage: 2Gi  
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
    path: /data/prometheus-alert-manager  