apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingress
  namespace: monitoring 
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`uptime.travismedia.cloud`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3001