---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.2-192.168.1.10 # change this to your allocated range
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-advertisement
  namespace: metallb-system