---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
data:
  api-token: your-api-token  # <-- Replace with your Cloudflare API token base64 encoded
# If you prefer not to base64 encode your token first, can use the below with the token as is
# stringData:
#   api-token: <API Token>