---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: traefik # we will set this as the default certificate for Traefik to use, thus the namespace
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - "*.yourdomain.com"
    - "yourdomain.com"